### ISSUE TITLE
Auto Generating Swagger API Docs

### ISSUE THREAD

**Issue by kamleshkatpara** [ljlm0402/typescript-express-starter#100]
Hi,

I found this starter template very helpful for the developer community.

I had a suggestion for auto generating swagger (api-docs) using the following below packages:

https://www.npmjs.com/package/routing-controllers

https://www.npmjs.com/package/routing-controllers-openapi

I believe once this starter template has this two included then it would be more helpful to save the developer's time in manually writing the swagger api docs.

**Comment by ljlm0402** [comment]
@kamleshkatpara 

Thank you for the good information.
For reference, I will try to improve just about the improvement points.

**Comment by kamleshkatpara** [comment]
@ljlm0402 When can you add this feature ?

**Comment by ljlm0402** [comment]
@kamleshkatpara 

I am sorry that it is open for personal reasons. 
I will update it this month. 
If you receive a pull request, we will discuss it and then reflect it.

**Comment by kamleshkatpara** [comment]
@ljlm0402 

Thank you for adding it,

Just to inform you that the swagger is not working as it should:

<img width="1663" alt="Screenshot 2021-07-17 at 10 12 37 AM" src="https://user-images.githubusercontent.com/16983847/126025891-101a172e-21e7-4a97-9bcd-af28689a12b9.png">


Also the difficult part would with be uploading files through swagger using routing-controllers-openapi.

I am making my own version of it using references will share with you once done.

**Comment by ljlm0402** [comment]
@kamleshkatpara 

Sorry about the error.
Newly updated.

I developed it referring to https://github.com/epiphone/routing-controllers-openapi/tree/master/sample, and after testing it was confirmed that it works normally.
Thank you.

▼ screenshot
![image](https://user-images.githubusercontent.com/42952358/126155764-30f07a84-79e1-46ce-b85e-098190f9983b.png)

![image](https://user-images.githubusercontent.com/42952358/126155827-2d6e038a-b26b-4902-8b91-a02d8d952579.png)

**Comment by kamleshkatpara** [comment]
@ljlm0402 Why you did not use typeorm in this ?

**Comment by ljlm0402** [comment]
@kamleshkatpara 

The typeorm template exists separately, and if you want to use the function in other templates, you will need to use it separately.
