### ISSUE TITLE
How to add global routes prefix

### ISSUE THREAD

**Issue by attiqueur-rehman** [ljlm0402/typescript-express-starter#105]
i want to add the global routes prefix as we do in plain express app with.

```
app.use("/prefix", routes);
```

using this project coding styles and ts how can we add a prefix to all routes available in application.

Thanks

**Comment by ljlm0402** [comment]
@attiqueur-rehman 

Just add the use prefix to the `initializeRoutes` function in `app.ts`.

![image](https://user-images.githubusercontent.com/42952358/125218070-11e8ba00-e2fd-11eb-92a8-866a65af3ea3.png)

**Comment by attiqueur-rehman** [comment]
yeah it works.

**Comment by ljlm0402** [comment]
@attiqueur-rehman 

I'm glad it's working normally. Thank you for using it.
