### ISSUE TITLE
Refresh Tokens

### ISSUE THREAD

**Issue by mweel1** [ljlm0402/typescript-express-starter#108]
### Motivation(새로운 기능 설명)

Right now a JWT is created with an expiration date.  If that expiration date the user will trip the auth middleware.

### Proposed Solution(기능을 통해 얻고자 하는 솔루션)

Create refresh tokens so the user can provide a refresh token on expiry and get a new JWT.

**Comment by genedy377** [comment]
hello @ljlm0402  @mweel1 My Name is Eslam Genedy . I am a software developer and I am so interested in contributing an open source ,so I hope to develop this feature and contribute this open source and thanks in advance .

**Comment by ljlm0402** [comment]
@genedy377 

Thank you very much for your contribution.
I look forward to :)

**Comment by ljlm0402** [comment]
@genedy377 

Hello.
Thank you very much for your contribution.

I'm curious to see how things are going, so I'll contact you.
