### ISSUE TITLE
Linting-Error(Outdated Package?): Module '"class-transformer"' has no exported member 'plainToClass'.ts, Ln1:Validation.middleware.ts

### ISSUE THREAD

**Issue by AbhinavRobinson** [ljlm0402/typescript-express-starter#125]
### Describe the Bug (버그 설명)

Module '"class-transformer"' has no exported member 'plainToClass'.ts(2305)

### Version to Reproduce (현재 사용한 버전)

Latest from npx (as of 25th Nov, 2021)

### Steps to Reproduce (재현 순서)

1. Go to Validation.middleware.ts
2. See error, no exported member plainToClass, Line 1

### Expected Behavior (예상 동작)

No such linting error should be present

### Actual Behavior (실제 동작)

Linting error from typescript, no such exported module plainToClass from class-transformer

### Additional Context (추가 사항)

N/A

### Capture screen (캡쳐 화면)

<img width="1088" alt="Screenshot 2021-11-25 at 12 44 21 PM" src="https://user-images.githubusercontent.com/32090909/143396304-d772d80c-c231-43a5-a7c4-4a67270ddeee.png">

**Comment by ljlm0402** [comment]
@AbhinavRobinson 

Check the version of the library to see if "plane To Class" exists or not, and if you don't, you can lower the library version and use it.

`"class-transformer": "^0.4.0",` 

![image](https://user-images.githubusercontent.com/42952358/145131990-77caab0e-995c-469f-8fb7-3f3fdbe70c78.png)

Also, by checking the class-transformer README, you can confirm that the method exists. Note please.

https://github.com/typestack/class-transformer#plaintoclass

**Comment by lindesvard** [comment]
Got this myself. Seems like they have removed it in `0.4.1` which we get since `^`.

Forcing it to get `0.4.0` solves the issue
