### ISSUE TITLE
Class transformer not working with swc

### ISSUE THREAD

**Issue by ljlm0402** [ljlm0402/typescript-express-starter#129]
### Describe the Bug (버그 설명)

- [Class transformer not working with swc](https://github.com/swc-project/swc/issues/2117)
- [Problems with decorators when using class validator](https://github.com/swc-project/swc/issues/1362)

### Capture screen (캡쳐 화면)

![image](https://user-images.githubusercontent.com/42952358/147225970-91739360-e008-42cb-8b76-bc63572cb478.png)

**Comment by peng-huang-cc** [comment]
Thank you for your work. 

Before fixing this issue, could you change the npm scripts?
The `npm run start` could not work.

change
```js
"build": "swc src -d dist --source-maps --copy-files",
"build:tsc": "tsc  && tsc-alias",
```
to
```js
"build:swc": "swc src -d dist --source-maps --copy-files",
"build": "tsc  && tsc-alias",
```

**Comment by ljlm0402** [comment]
@peng-huang-cc 

npm script is based on tsc build as before.

We will change it again later when the patch is completed in swc. thank you.
