### ISSUE TITLE
Cannot even start the project

### ISSUE THREAD

**Issue by clifflo** [ljlm0402/typescript-express-starter#147]
When I installed the program and runs it I cannot even start up the project. The project just said "odemon] app crashed - waiting for file changes before starting...". How to fix that?

**Comment by ljlm0402** [comment]
@clifflo 

to determine the exact cause, Please check the error log in the logs folder and take a screenshot.

**Comment by JagTheFriend** [comment]
> When I installed the program and runs it I cannot even start up the project. The project just said "odemon] app crashed - waiting for file changes before starting...". How to fix that?

Check whether the `.env.development.local` file exists and whether it also has:
```env
# PORT
PORT = 3000

# TOKEN
SECRET_KEY = secretKey

# LOG
LOG_FORMAT = dev
LOG_DIR = ../logs

# CORS
ORIGIN = *
CREDENTIALS = true
```

**Comment by alastairblackwood** [comment]
I'm getting same issue too... this is what error logs show. Seems to be demanding latest version of Mongoose...

![Screenshot 2022-03-07 at 22 22 29](https://user-images.githubusercontent.com/80987175/157033804-49df8f65-b3b1-45de-849c-dadca32895ed.png)

**Comment by alastairblackwood** [comment]
I'm trying to use it with Typegoose too... which I assume will need to be updated at the same time to work together?

**Comment by JagTheFriend** [comment]
> I'm trying to use it with Typegoose too... which I assume will need to be updated at the same time to work together?

No, the Typegoose docs explicitly mentions that  mongoose 6.2.3 or higher is required for it to work properly due to major changes in the newer versions (of Typegoose).
Have a look at:
https://typegoose.github.io/typegoose/docs/guides/error-warning-details/#mongoose-version-e001

**Comment by alastairblackwood** [comment]
Thanks @JagTheFriend

The server starts up now, but when I try to connect it with my MongoDB Compass database it produces this error..

I've placed the connection string into DB_DATABASE in the .env.development.local file. Is that the correct place it needs to go? Many thanks.

![Screenshot 2022-03-08 at 09 38 57](https://user-images.githubusercontent.com/80987175/157136747-0435151b-65f7-47ea-9646-c8797b045f3f.png)
.

**Comment by JagTheFriend** [comment]
@alastairblackwood No, you're not suppose to put the connection string in `DB_DATABASE` variable.
Try use this as your `.env.development.local` instead: 
```
# PORT
PORT = 3000

# DATABASE
DB_HOST = localhost
DB_PORT = 27017
# NOTE: This the name of the collection, 
# and not the connection string
DB_DATABASE = test

# TOKEN
SECRET_KEY = secretKey

# LOG
LOG_FORMAT = dev
LOG_DIR = ../logs

# CORS
ORIGIN = *
CREDENTIALS = true
```

**Comment by JagTheFriend** [comment]
@clifflo Btw, is your issue fixed?

**Comment by alastairblackwood** [comment]
> @alastairblackwood No, you're not suppose to put the connection string in `DB_DATABASE` variable. The `DB_DATABASE` variable is being used for storing the name of the collection Try use this as your `.env.development.local` instead:
> 
> ```shell
> # PORT
> PORT = 3000
> 
> # DATABASE
> DB_HOST = localhost
> DB_PORT = 27017
> # NOTE: This the name of the collection, 
> # and not the connection string
> DB_DATABASE = test
> 
> # TOKEN
> SECRET_KEY = secretKey
> 
> # LOG
> LOG_FORMAT = dev
> LOG_DIR = ../logs
> 
> # CORS
> ORIGIN = *
> CREDENTIALS = true
> ```

Thanks @JagTheFriend ,

With those default credentials,  the server starts up, but it doesn't resolve my issue of trying to add my MongoDB Compass/Atlas connection string so I can start using my cloud database storage. Do I need to keep the credentials above and create a new value into the .env file instead?

Many thanks.

**Comment by alastairblackwood** [comment]
@JagTheFriend  Managed to fix it up... just created my own value (MONGO_URI) in .env file and removed existing ones in databases & config index.ts files. Connecting to MongoDB with no issues now. 

Many thanks.

**Comment by JagTheFriend** [comment]
@alastairblackwood Yea, i think you'd create a new value inside the `.env` to store the connection string,
and also change [this file](https://github.com/ljlm0402/typescript-express-starter/blob/master/lib/typegoose/src/databases/index.ts#L1-#L3)
to something like: 
```ts
// Assuming that `MONGO_URI` stores the connection string, you can do this;
export const dbConnection = process.env.MONGO_URI;
````

**Comment by JagTheFriend** [comment]
@alastairblackwood Any updates?

**Comment by alastairblackwood** [comment]
No updates… it’s working perfectly now! Such a beautiful design. Thank you!

**Comment by ljlm0402** [comment]
@clifflo @JagTheFriend @alastairblackwood 

Sorry for the late reply due to busy circumstances. We will update soon. thank you.

**Comment by JagTheFriend** [comment]
> No updates… it’s working perfectly now! Such a beautiful design. Thank you!

Np 😊

**Comment by ljlm0402** [comment]
@alastairblackwood 

Hello. Thank you for leaving the issue.
I have confirmed the issue for that issue.
Please look at the example below and ask for comments.

env file
```bash
# DATABASE
DB_HOST = localhost
DB_PORT = 27017
DB_DATABASE = test
```

config file
```
import { config } from 'dotenv';
config({ path: `.env.${process.env.NODE_ENV || 'development'}.local` });

export const { DB_HOST, DB_PORT, DB_DATABASE } = process.env;
```

database file
```sh
import { DB_HOST, DB_PORT, DB_DATABASE } from '@config';

export const dbConnection = `mongodb://${DB_HOST}:${DB_PORT}/${DB_DATABASE}`;
```

Like this example, you are exported from the CONFIG with data to the current Env file.

However, I wonder why you want to currently want Mongo_uri Env data.

Is there a problem with that code or having another problem?

Except for the Mongose ​​version.

The screenshot below is the result of testing without modifying the env.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/42952358/158337079-b47966d7-033b-4e73-aac4-ade385afdf2f.png">

**Comment by codermug** [comment]
Hey!
I found a solution by stopping all node process and restart the server
please check:
https://harsh-patel.medium.com/nodemon-app-crashed-waiting-for-file-changes-before-starting-47951f84c79b
