### ISSUE TITLE
How do we add new migration?

### ISSUE THREAD

**Issue by reaganscofield** [ljlm0402/typescript-express-starter#151]
### Summary (요약)

assumed that's we already have a table that exists in production, so now we decided to add a new column to that table how do we do this? because it seems like once the table is created and you add a new column on the model it's not gonna going to add that column on the database, in order to archive this we basically need to create a new migration file that will add the column to the existing table.

thank you for the response in advance

**Comment by ljlm0402** [comment]
@reaganscofield 

I will answer the question after the investigation.

thank you.
