### ISSUE TITLE
 Create a new template Postgresql-typescript

### ISSUE THREAD

**Issue by JagTheFriend** [ljlm0402/typescript-express-starter#164]
### Motivation (새로운 기능 설명)

Create a new template postgress-typescript

**Comment by ljlm0402** [comment]
@JagTheFriend 

hello.

There are questions about issues.
Is there an ORM separately in "postgess-typescript" requested?
If not, do you want a template with pg?

Thank you for your document or link.

**Comment by JagTheFriend** [comment]
@ljlm0402 

> Is there an ORM separately in "postgess-typescript" requested?

Sure _(if possible)_
Maybe this would help: [Building and running a Node.JS, TypeScript, PostgreSQL app with Docker](https://medium.com/nsoft/building-and-running-nodejs-typescript-postgresql-application-with-docker-3878240a2f73)
