### ISSUE TITLE
Error: Cannot find module 'ts-jest/utils'

### ISSUE THREAD

**Issue by ljlm0402** [ljlm0402/typescript-express-starter#167]
### Describe the Bug (버그 설명)

"npm run test" When running, error

### Version to Reproduce (현재 사용한 버전)

- node: v16.13.0
- npm: v8.10.0

### Capture screen (캡쳐 화면)

<img width="816" alt="image" src="https://user-images.githubusercontent.com/42952358/170506598-9142b944-9b43-4d9a-bcaa-ae328f9c989e.png">

**Comment by deborez** [comment]
It works for me when I changed my import from "ts-jest/utils" by "ts-jest" in "jest.config.js".

In the new version of ts-jest (V28), "utils" folder doesn't exists anymore.

**Comment by ljlm0402** [comment]
@deborez 

Thank you for your help.
