### ISSUE TITLE
Tests fail for typeorm template

### ISSUE THREAD

**Issue by jordanator** [ljlm0402/typescript-express-starter#168]
### Describe the Bug (버그 설명)
Created a new project with typeorm template and ran the tests but got the following error for `user.test.ts` and `auth.test.ts`

`Property 'users' does not exist on type 'UserService'`
`Property 'users' does not exist on type 'AuthService'`

Please find the screenshot below for more details

### Version to Reproduce (현재 사용한 버전)
NodeJS => 16.15.1
NPM => 8.11.0
Typescript => 4.5.2

### Steps to Reproduce (재현 순서)
1. Create project with **typeorm** template
2. `cd` into project
3. Run `npm run test`

### Expected Behavior (예상 동작)
All tests should pass

### Actual Behavior (실제 동작)
Tests fail with the following errors

`Property 'users' does not exist on type 'UserService'`
`Property 'users' does not exist on type 'AuthService'`

### Capture screen (캡쳐 화면)

![2022-06-09_11-08_1](https://user-images.githubusercontent.com/1297263/172780193-554103c0-626c-4ae2-9169-e2a8b628b730.png)

**Comment by ljlm0402** [comment]
@jordanator 

The issue has been confirmed. Please correct it. 
thank you :-)
