### ISSUE TITLE
Please acknowledge where you copied this project from

### ISSUE THREAD

**Issue by seanpmaxwell** [ljlm0402/typescript-express-starter#18]
This exact line is from my readme in express-generator-typescript

"Node Js is great for the rapid development of web-projects, but is often neglected because of the lack of type safety. TypeScript solves this issue and (along with its linter file) can even make your code more robust than some other static languages like Java." Plus a huge chunk of other code is identical.

I know express-generator-typescript is an open source project but at least acknowledge your project as a fork/variation of mine you're going to copy me line-by-line.

**Comment by ljlm0402** [comment]
@seanpmaxwell 

I apologize for the unauthorized copying of Project Lead Me. We will edit the text as requested. I'm really sorry.

**Comment by ljlm0402** [comment]
@seanpmaxwell 

Also thank you additionally good material. The material is so good that I apologize once again for the eyeballs and copying.

**Comment by seanpmaxwell** [comment]
Sorry didn't mean to come of as harsh. Thanks for the apology. It's an open-source MIT licensed project so I don't mind at all you copying the project and making it better. All I would like you to do is mention at the top of the readme which project you are building off of. Just a single sentence which mentions this is fork of the project 'express-generator-typescript' located at https://github.com/seanpmaxwell/express-generator-typescript. And where good 👍

**Comment by seanpmaxwell** [comment]
I created a pull request to mention where the project is being built upon from. This is the only change that I ask you do. You don't need to update the entire readme.

**Comment by seanpmaxwell** [comment]
I saw your change. Thanks for mentioning me in the readme. I'm closing this issue.

**Comment by ljlm0402** [comment]
@seanpmaxwell 

As a result, we have revised the README. It's different from the pull request, but ask if it's ok.

Please reply with a translator, please understand.

![image](https://user-images.githubusercontent.com/42952358/75843195-e48d2180-5e15-11ea-89db-3fea236a0aab.png)

**Comment by seanpmaxwell** [comment]
Looks great!
