### ISSUE TITLE
switch tslint to eslint

### ISSUE THREAD

**Issue by weakish** [ljlm0402/typescript-express-starter#2]
[TypeScript is switching from tslint to eslint][switch], will typescript-express-starter consider to output a project with eslint.

[switch]: https://eslint.org/blog/2019/01/future-typescript-eslint

**Comment by ljlm0402** [comment]
@weakish 
Thank you for your help. I will change it later.

**Comment by ljlm0402** [comment]
@weakish 
Hi, Bro I have something to ask
Can you see why the trend is moving from tslint to eslint?
