### ISSUE TITLE
Cannot launch express-typescript-mongoose project on my local

### ISSUE THREAD

**Issue by healer-1205** [ljlm0402/typescript-express-starter#220]
### Version to Reproduce 

My current node version is 16.20.1

### Steps to Reproduce 

When installing the module is done, I run the **npm start** command, but this error happened.
![image](https://github.com/ljlm0402/typescript-express-starter/assets/91068182/cecb3892-7502-42d5-a226-2356179b3f5f)

I tried to install **@databases** npm to fix this but this error happened.

![image](https://github.com/ljlm0402/typescript-express-starter/assets/91068182/9181bada-bf9e-435c-b35d-e2ebfa169bae)

**Comment by Elozzy** [comment]
Hello @kashif-ghafoor @healer-1205  I found a solution for it. 
Just import the dbConnection path like this `import { dbConnection } from './database/index';`

**Comment by ljlm0402** [comment]
@healer-1205 

The fix has been completed and the issue has been closed.
