### ISSUE TITLE
Sensitive case for '@exceptions/httpException'

### ISSUE THREAD

**Issue by roco170a** [ljlm0402/typescript-express-starter#222]
### Describe the Bug (버그 설명)

When work in linux, this file show a error of  MODULE MISSING, and the reason is that the file begin with UpperCase but in the code is in lower case

### Version to Reproduce (현재 사용한 버전)

Linux Ubuntu

### Steps to Reproduce (재현 순서)

1.- Login into linux.
2.- Install the solution and run
3.- execute NPM RUN DEV
4.- into LOG directory show a MODULE MISSING

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).
-->

### Expected Behavior (예상 동작)

Run as smooth posible

### Actual Behavior (실제 동작)

Operative system didnt find exceptions/httpException because have diferente case sentitive

### Additional Context (추가 사항)

Linux Ubuntu OS

**Comment by ljlm0402** [comment]
@roco170a 

The fix has been completed and the issue has been closed.
