### ISSUE TITLE
Feature Request: Sequelize-cli Integration

### ISSUE THREAD

**Issue by jktzes** [ljlm0402/typescript-express-starter#23]
Hi guys! Great work on this project! Thanks for saving me a lot of headaches!

If there could be some `sequelize-cli` integration on this project(to generate migration and etc), or document on how to set it up, it'd be great! Thanks again for your work.

**Comment by ljlm0402** [comment]
@jktzes 
Thanks for the issue. We will try to reflect the requested content after confirmation.
