### ISSUE TITLE
Feature Request : Make Things Optional

### ISSUE THREAD

**Issue by EmreSURK** [ljlm0402/typescript-express-starter#28]
We need a project that just works right after created. That helps to make trying things extremely easy and so attracts more people.  That project fits me almost perfectly, no Passport things, creates auth and DB stuff, and so on. But, not including Pug is a minus.
I believe, if we can make these things optional we can put that project as an industry standard that helps people to code Node with TS.

**Comment by ljlm0402** [comment]
@EmreSURK 
This starter is a starter for RESTful API. 
The internal template pub is not supported. Sorry.
