### ISSUE TITLE
No swagger.yaml

### ISSUE THREAD

**Issue by yadirhb** [ljlm0402/typescript-express-starter#29]
Hey guys I just created a project via npx and I was trying to get in to the swagger in the scratch project and it not working. There is no even a swagger.yaml file.

**Comment by ljlm0402** [comment]
@yadirhb 
Sorry. Currently the swagger.yaml file only exists in the default template. 
We will add it to other templates as soon as possible.

**Comment by malavancs** [comment]
@ljlm0402 are you accepting any open source contributors ?

**Comment by ljlm0402** [comment]
@malavancs 

of course. Welcome contributors.
