### ISSUE TITLE
generated issue

### ISSUE THREAD

**Issue by Zanooza** [ljlm0402/typescript-express-starter#30]
✖ Please leave this error as an issue
Error: Command failed: npm i -s bcrypt class-transformer class-validator cookie-parser cors cross-env dotenv envalid express helmet hpp jest jsonwebtoken morgan swagger-jsdoc swagger-ui-express ts-jest ts-node typescript mysql2 sequelize sequelize-typescript

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm i -s bcrypt class-transformer class-validator cookie-parser cors cross-env dotenv envalid express helmet hpp jest jsonwebtoken morgan swagger-jsdoc swagger-ui-express ts-jest ts-node typescript mysql2 sequelize sequelize-typescript',
  stdout: "Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/asya/prjcts/adminkoSwaponline/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/asya/prjcts/adminkoSwaponline/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)\n",
  stderr: ''
}

**Comment by ljlm0402** [comment]
@Zanooza 
Can you know the node.js version and npm version?
