### ISSUE TITLE
Support GraphQL template

### ISSUE THREAD

**Issue by thanhlam2410** [ljlm0402/typescript-express-starter#35]
Do you consider to support GraphQL template in future?

**Comment by ljlm0402** [comment]
@thanhlam2410 

Thanks for the good issue. We are planning to develop GraphQL template after developing the Typeorm template.

**Comment by thanhlam2410** [comment]
I'm a fan of mongoose and and express and still happy with them till now but I'm happy to switch to new template with GraphQL + mongoose/sequelize when you support them

**Comment by ljlm0402** [comment]
The issue will be developed as a new project.
