### ISSUE TITLE
Problem creating id value automatically when user is added

### ISSUE THREAD

**Issue by swtpumpkin** [ljlm0402/typescript-express-starter#4]
auto increment not applied

**Comment by Jorgeptz** [comment]
incremento automático aplicado

**Comment by Jorgeptz** [comment]
struct audio_hw_device {
    struct hw_device_t common;

    / **
     * utilizado por flinger de audio para enumerar qué dispositivos son compatibles con
     * cada implementación de audio_hw_device.
     * *
     * El valor de retorno es una máscara de bits de 1 o más valores de audio_devices_t
     * /
    uint32_t (* get_supported_devices) (const struct audio_hw_device * dev);
  ...
};
typedef struct audio_hw_device audio_hw_device_t;
