### ISSUE TITLE
Feature Request : Support for validationMiddleware on query params

### ISSUE THREAD

**Issue by malavancs** [ljlm0402/typescript-express-starter#40]
Currently validation middleware only works on req.body. It will be good if have an option to specify what needs to validated.

**Comment by ljlm0402** [comment]
@malavancs 

If it is an option you specify, do you mean req.query, req.params?

**Comment by malavancs** [comment]
Currently in plainToClass(type,req.body) is default. It should allow us to specify whether it is a **body** or **query** or **params** in function parameters.

Its a nice have option I guess.

```js
function validationMiddleware(type: any, skipMissingProperties = false): RequestHandler {
  return (req, res, next) => {
    validate(plainToClass(type, req.body), { skipMissingProperties })
    .then((errors: ValidationError[]) => {
      if (errors.length > 0) {
        const message = errors.map((error: ValidationError) => Object.values(error.constraints)).join(', ');
        next(new HttpException(400, message));
      } else {
        next();
      }snippets
    });
  };
}
```



PS: I will make a pull request for this soon .

**Comment by ljlm0402** [comment]
@malavancs 

Thank you Bro.

**Comment by malavancs** [comment]
@ljlm0402 I'm not able to make pull request. Can you add me ?
