### ISSUE TITLE
Unit Tests Errors describe logout (cookie)

### ISSUE THREAD

**Issue by ljlm0402** [ljlm0402/typescript-express-starter#53]
### Describe the Bug

Cookie data does not exist, causing middleware errors

### Steps to Reproduce

auth.test.ts files describe logout

### Capture screen

![image](https://user-images.githubusercontent.com/42952358/101583980-f5f7ff80-3a1f-11eb-9962-7ecb8a494d77.png)

**Comment by nubilfi** [comment]
I don't know is that a bug or not, I figured out how to passed the test, but with a little side note.
Since the middleware is checking the `valid` userId and header `cookie`, we have to change the user `id` inside the assertion to the real user `id` in the database then set the `cookie`.

```
describe('[POST] /logout', () => {
    // NOTE:
    // make sure there is a user with the same ID in database
    it('logout Set-Cookie Authorization=; Max-age=0', async () => {
      const user: User = {
        id: 2,
        email: 'test@email.com',
        password: 'q1w2e3r4',
      };

      const authRoute = new AuthRoute();
      const users = authRoute.authController.authService.users;
      const tokenData = authRoute.authController.authService.createToken(user);
      const cookie = authRoute.authController.authService.createCookie(tokenData);

      users.findFirst = jest.fn().mockReturnValue({
        ...user,
        password: await bcrypt.hash(user.password, 10),
      });

      const app = new App([authRoute]);
      return request(app.getServer())
        .post(`${authRoute.path}logout`)
        .set('Cookie', [cookie])
        .expect('Set-Cookie', /^Authorization=\;/);
    });
  });
```

You might want to mock the middleware though or just use my example :jack_o_lantern:

**Comment by ljlm0402** [comment]
@nubilfi 

Thanks for letting us know about the notes. Let's see if there is a better way. First, consider a known issue.
