### ISSUE TITLE
npx typescript-express-starter  => Cannot destructure property `readdir` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by akshayshikre** [ljlm0402/typescript-express-starter#55]

**Comment by akshayshikre** [comment]
HI 
i installed npm globally now i am generating project but it giving me error

```
npx typescript-express-starter vault-api
Cannot destructure property `readdir` of 'undefined' or 'null'.
```

**Comment by ljlm0402** [comment]
@akshayshikre 

I could not understand exactly about your situation.
Let's see if you want to let you know version. Thank you.

▼ Capture screen
![image](https://user-images.githubusercontent.com/42952358/102674323-f9864600-41d8-11eb-8eab-0691bcea258e.png)

**Comment by tarun7singh** [comment]
I faced same issue but was able to **resolve** it by updating my node version. 
The issue came on node v8.17.0
and was resolved by updating to the latest node version.

**Comment by ljlm0402** [comment]
@tarun7singh 
Thanks for a good answer.

@akshayshikre 
Thank you if you are going to proceed after updating the Node version.
I will also do not know the version of version in the future.

**Comment by akshayshikre** [comment]
Thank you, i will try after Node.js updation
