### ISSUE TITLE
Unable to use postgresql with this

### ISSUE THREAD

**Issue by theabhinavdas** [ljlm0402/typescript-express-starter#56]
Tried to set sequelize during the setup. Later, modified the configs and environments to use `postgres` but that doesn't allow me to use my postgresql server :( Am I doing it incorrectly?

**Comment by ljlm0402** [comment]
@theabhinavdas 

Please give me a screenshot or detailed explanation of the situation.

**Comment by codingpop** [comment]
@theabhinavdas Try deleting your local Docker image of the server and create another one. That's what to fix the problem
