### ISSUE TITLE
Jest unit test fails

### ISSUE THREAD

**Issue by praveen-jha-by** [ljlm0402/typescript-express-starter#59]
### Describe the Bug

yarn test or "npm run test" fails connect method of mongoose cannot be mocked.
As a result all of the test cases fail.

### Steps to Reproduce

npm install -g typescript-express-starter
npx typescript-express-starter nodeExpressTsSample
npm run test

### Expected Behavior

The test cases should pass.

### Actual Behavior

Test cases fail with error:
**TypeError: Cannot read property 'then' of undefined**
     mongoose_1.connect(database_1.dbConnection.url, database_1.dbConnection.options)
    .then(() => {
    ^
     logger_1.logger.info('🟢 The database is connected.');

If applicable, add screenshots to help explain your problem. -->

### Capture screen

![image](https://user-images.githubusercontent.com/63631847/104283700-efedb680-54d6-11eb-94fc-48a80392bf92.png)

**Comment by ljlm0402** [comment]
@praveen-jha-by 

Thanks for the good Issues.
This is currently under review, and if you use the async/await syntax, it will work normally.
