### ISSUE TITLE
NODE_ENV

### ISSUE THREAD

**Issue by vraimentres** [ljlm0402/typescript-express-starter#6]
안녕하세요.

app 시작시 enum 타입의 node_env 를 가지면 추후 활용할 점이 있을것 같습니다~

```
enum NodeEnv {
  development = 'development',
  production = 'production',
}
```

**Comment by ljlm0402** [comment]
@vraimentres 
좋은 이슈 감사합니다. 추후에 업데이트 하겠습니다.

**Comment by ljlm0402** [comment]
@vraimentres 
좋은 이슈 남겨주신거에 대해 우선 감사의 말씀을 드립니다.
앞서 말하신 enum 타입 활용 방안에 대해서 생각을 해보다가 우선적으로 node_env를 빠르게 활용할 다른 방법을 모색하여 업데이트를 해놓은 상태입니다. 좀더 검토해보면서 추가적인 사항 말씀드리겠습니다. 감사합니다. :)

**Comment by vraimentres** [comment]
@ljlm0402 제가 생각했던 enum 방식보다 더 좋은것같습니다! 감사합니다 ~
