### ISSUE TITLE
Build fails when using TypeORM installation.

### ISSUE THREAD

**Issue by NeuralChris** [ljlm0402/typescript-express-starter#64]
### Describe the Bug(버그 설명)

After creating the project `npx typescript-express-starter [project name]` and running `npm i`.  Running `npm start` builds the project, but when node tries to run the built output, it spits out this error.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/chris/Projects/NodeAPI/node_modules/swagger-jsdoc/index.js
require() of ES modules is not supported.
require() of /Users/chris/Projects/NodeAPI/node_modules/swagger-jsdoc/index.js from /Users/chris/Projects/NodeAPI/build/app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/chris/Projects/NodeAPI/node_modules/swagger-jsdoc/package.json.
```

### Version to Reproduce(현재 사용한 버전)

This was running on a Mac using Node 14.15.5

### Expected Behavior(예상 동작)

I expect the project to build and run successfully even if it can't connect to a database or anything.

### Actual Behavior(실제 동작)

The error shown above.

**Comment by NeuralChris** [comment]
As a matter of fact, your sequelize template has this issue too.

**Comment by Steffen93** [comment]
I had a similar issue with swagger-jsdoc on the mongoose template. Problem for me seemed to be a version mismatch between the "swagger-jsdoc" dependency (was version "^7.0.0-rc2") and the devDependency "@types/swagger-jsdoc" had version "^6.0.0". So I uninstalled swagger-jsdoc and re-installed version 6.0.0 like so:

`npm uninstall swagger-jsdoc
npm install --save swagger-jsdoc@6.0.0`

After those changes it worked for me.

**Comment by ljlm0402** [comment]
@NeuralChris  @Steffen93 

We sincerely apologize for the error.

The cause of the problem was explained by Steffen93, and the version was specified as a countermeasure.
Since the open source is installed based on the latest version, we apologize for not considering that part, and we will pay more attention to the module compatibility part. Thank you.

* Sorry that the sentences are not smooth using the translator.
