### ISSUE TITLE
.gitignore file is not creating

### ISSUE THREAD

**Issue by shiva-sandupatla** [ljlm0402/typescript-express-starter#79]
when i use `npx typescript-express-starter "my project name"`, it is creating all template files but not .gitignore file.

Is this a problem for me only, 

hope you rectify it.

Regards, @shiva-sandupatla

**Comment by vivek7405** [comment]
I too am facing the same issue. Any update on this?

**Comment by vivek7405** [comment]
Can I get the .gitignore file until this bug is fixed?

**Comment by ljlm0402** [comment]
@shiva-sandupatla @vivek7405

Sorry for the late reply. We will respond promptly after confirmation.

**Comment by ljlm0402** [comment]
@vivek7405 

The desired .gitignore file. We will identify the cause and inform you as soon as possible.

link: https://gist.github.com/ljlm0402/2e388901778172b0dbb796eececd4e86

**Comment by vivek7405** [comment]
@ljlm0402 Thanks for the link. Much helpful!

**Comment by shiva-sandupatla** [comment]
Hope you will fix it. @ljlm0402
