### ISSUE TITLE
Can i add sequelize-typescript and refactor the existing code for models?

### ISSUE THREAD

**Issue by edward-teixeira** [ljlm0402/typescript-express-starter#88]
### Summary(요약)

It's a lot easier and less verbose to configure sequelize models using data annotaions and some utitilities provides by sequelize-typescript.

### Additional Details(추가적인 세부 사항)

Reference: https://github.com/RobinBuschmann/sequelize-typescript

**Comment by ljlm0402** [comment]
@edward-teixeira 

The current sequelize template was developed using the previous sequelize-typescript.
However, as the version of sequelize went up, a bug occurred about the dependency accordingly, and for now, it was developed using sequlize.
If you use sequelize-typescript by fixing the sequlize version to @6, there will be no problem.
Let's think a little more about this.

**Comment by edward-teixeira** [comment]
Ok then
