### ISSUE TITLE
Starting the app throws an error (Ubuntu)

### ISSUE THREAD

**Issue by claudesortwell** [ljlm0402/typescript-express-starter#89]
### Describe the Bug(버그 설명)

Anytime you tired to npm start (or run the built server), it would fail with:
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module './'
Require stack:
```

### Version to Reproduce(현재 사용한 버전)

Ubuntu 20.04, Node v12.22.1, npm v6.14.12

### Steps to Reproduce(재현 순서)

1. Start a new project with Prisma
2. Run npm install
3. Run npm start

### Expected Behavior(예상 동작)

Its expected to start the server up on port 3000 but fails.

### Actual Behavior(실제 동작)

Fails and quits server.

### Additional Context(추가 사항)

I fixed this by changing line 4 of server.ts from:
```
import App from '@app';
```
to:
```
import App from './app';
```

### Capture screen(캡쳐 화면)

![image](https://user-images.githubusercontent.com/41422239/115794212-f6ae9280-a410-11eb-9a75-a85b07c569b3.png)

**Comment by ljlm0402** [comment]
@claudesortwell 

Thank you for leaving the bug issue.

After confirming this issue, we will take action.

**Comment by chrisurlaub** [comment]
I experienced the same issue using node v15.13.0 and after I switched to v13.11.0 everything worked well.

(though I had to install package "pg" manually to work with sequelize and postgresql)

**Comment by timothystewart6** [comment]
The same happens for me after a build.  It also happens when putting it in a docker container.  I am using node `14.16.1`

**Comment by timothystewart6** [comment]
I think I made some progress.  It seems like it might be `tsc-alias` which I haven't used before but I can see how it's conveneint.  I replaced all aliases with relative imports and built, then passed in vaiabled manually as a test.  The app started from the transpiled version immediately.

```bash
NODE_ENV=development PORT=3000 node server.js
```
```bash
2021-05-02 00:08:48 info: =================================
2021-05-02 00:08:48 info: ======= ENV: development =======
2021-05-02 00:08:48 info: 🚀 App listening on the port 3000
2021-05-02 00:08:48 info: =================================
```

I would like to use `tsc-alias` but not sure how to build a transpiled app with it.  Thanks for this by the way.  it's a great started kit.
