### ISSUE TITLE
when  i use npx typescript-express-starter "project name"

### ISSUE THREAD

**Issue by shiva-sandupatla** [ljlm0402/typescript-express-starter#90]
The files are creating and after sometime it says as below

```

× Please leave this error as an issue
Error: Command failed: npm i -s  bcrypt class-transformer class-validator compression config cookie-parser cors cross-env dotenv envalid express helmet hpp jest jsonwebtoken morgan swagger-jsdoc@6.0.0 swagger-ui-express ts-jest ts-node typescript winston winston-daily-rotate-file

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm i -s  bcrypt class-transformer class-validator compression config cookie-parser cors cross-env dotenv envalid express helmet hpp jest jsonwebtoken morgan swagger-jsdoc@6.0.0 swagger-ui-express ts-jest ts-node typescript winston winston-daily-rotate-file',
  stdout: '',
  stderr: ''
}

```

**Comment by ljlm0402** [comment]
@shiva-sandupatla 

Thank you for leaving the bug issue.

However, there seems to be a lack of information to figure out the exact cause.

I would appreciate it if you could describe it based on the contents of the bug template of the problem template.

---

Issues -> New Issues -> Bug Report [Get started]

![image](https://user-images.githubusercontent.com/42952358/115981081-34a3e600-a5cc-11eb-84da-e36a9019140c.png)

**Comment by shiva-sandupatla** [comment]
again when i delete generated files and freshly started by `npx typescript-express-starter "project name"` it worked fine. 

may be the problem is from my side
