### ISSUE TITLE
Modify Request type to include typed body

### ISSUE THREAD

**Issue by MuathAmer** [ljlm0402/typescript-express-starter#93]
### Summary(요약)

Even though there exists a `validationMiddleware` that calls `plainToClass()` and transforms the body object into a class instance, this class instance is not preserved and will need to be transformed again in the route handler.

### Additional Details(추가적인 세부 사항)

What currently exists in the project in the controller is a simple cast `const userData: CreateUserDto = req.body;`, but that's lying to the compiler because `userData` is not actually an instance of `CreateUserDto`, this can be noticed if the Dto has methods or custom getters or setters. Is this a real concern? Or should we ignore this?
One replacement could be `const userData = plainToClass(CreateUserDto, req.body);`, but I was thinking that maybe we can make use of the `validationMiddleware` as it calls `plainToClass` already.

What do you think?

**Comment by ljlm0402** [comment]
@MuathAmer 

We apologize for not understanding the delivery of the content due to a translation problem.
Do you care about the reason why the interfaces and dto objects are separated?

**Comment by MuathAmer** [comment]
@ljlm0402 
Here is what I am currently doing in `validation.middleware.ts`:
``` ts
const validationMiddleware = (
  type: any,
  value: string | "body" | "query" | "params" = "body",
  skipMissingProperties = false,
  whitelist = true,
  forbidNonWhitelisted = true
): RequestHandler => {
  return (req: ValidatedRequest<any>, res, next) => {
    const validated = plainToClass(type, (req as any)[value]);
    req.validatedBody = validated;  // Attach the validated body to the request
    validate(validated, {
      skipMissingProperties,
      whitelist,
      forbidNonWhitelisted,
    }).then( ...... )
```

And in `request.interface.ts` I have:
``` ts
export interface ValidatedRequest<T> extends Request {
  validatedBody: T;
}
```

And in one of my routes I do like this:
``` ts
signupRouter.post(
  "/",
  validationMiddleware(SignupDto),
  async (req: ValidatedRequest<SignupDto>, res, next) => { .....
```

I think that this is a better way to use the validated type in the request instead of the current approach, which casts the `req.body` to the dto type, which is not the proper way to use validated bodies.
It's not a big problem but just a small improvement.

**Comment by ljlm0402** [comment]
@MuathAmer 

Oh thank you very much. We will test and review your suggestions, 
but I think your suggestions are really good. If you leave a pull request, we will improve it quickly.

**Comment by MuathAmer** [comment]
@ljlm0402 
There is no reason it won't work as far as I see. Is your concern about the type safety of `validatedBody: CreateUserDto` when setting `skipMissingProperties = true`? If so, I think that's fine as long as the programmer realizes that some properties in the DTO (`validatedBody`) are optional, and this can also apply to the implementation as so:

``` ts
export class CreateUserDto {
  @IsEmail()
  public email?: string;

  @IsString()
  public password?: string;
}
```
Notice the `?` optional operator above.

Or you can have separate `CreateUserDto` and `UpdateUserDto`, and the programmer might use class-validator's `IsOptional()` decorator or setting `skipMissingProperties = true`, both are valid options for `UpdateUserDto`, but at this point that's `class-validator`'s knowledge.
