### ISSUE TITLE
Cannot see the actual error messages . 

### ISSUE THREAD

**Issue by surpriso1997** [ljlm0402/typescript-express-starter#96]
### Describe the Bug(버그 설명)

The only error message received while running the project is : 
```
[nodemon] app crashed - waiting for file changes before starting...
```

### Version to Reproduce(현재 사용한 버전)
4.3.1

### Steps to Reproduce(재현 순서)
1. create default project using the cli
2. Run : npm run dev , at this stage project runs fine. 
3. Create a typo in any .ts file for example: server.ts . Then save the file. 
4.  [nodemon] app crashed - waiting for file changes before starting...  , this error message is received.

This is a simple replication but not knowing what error occurred and where it occurred is really difficult to debug. 

### Expected Behavior(예상 동작)
The error messages should show the stack trace not just single line saying app has crashed.

```ReferenceError: AuthRout is not defined
    at Object.<anonymous> (/home/user/Documents/projects/node/typescript-express-starter/src/server.ts:12:13)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

### Actual Behavior(실제 동작)
Only this error message is displayed:
```
[nodemon] app crashed - waiting for file changes before starting...
```

### Additional Context(추가 사항)
node version:14.17.0
operating system: ubuntu 20.04

### Capture screen(캡쳐 화면)
screen recording:
https://imgur.com/a/jEHKwAH

https://ibb.co/RBWdb9Y

**Comment by ljlm0402** [comment]
@surpriso1997 

Thank you for Issues.
You can check the error log in the log folder.
debug log is a type that collects console line by line and other logs in a log file.
