### ISSUE TITLE
Create new Prisma template (Using Windows CMD)

### ISSUE THREAD

**Issue by SayerAljohani** [ljlm0402/typescript-express-starter#99]
### Describe the Bug(버그 설명)
When I set up a new Prisma template, the generation process is failed after a while. 
### Version to Reproduce(현재 사용한 버전)

Window 10, Node 14.6, NPM 6.14

### Steps to Reproduce(재현 순서)

1. Run this command  "npx typescript-express-starter myapp" 
2. Select Prisma template 
3. Then press Enter. 

### Expected Behavior(예상 동작)
 Created a project based on the selected template  and the process is completed without error"√ Complete setup project"

### Actual Behavior(실제 동작)

 X:\temp> npx typescript-express-starter myapppp
? Select a templates prisma
[ 1 / 3 ] 🔍  copying project...
[ 2 / 3 ] 🚚  fetching dependencies...
[ 3 / 3 ] 🔗  linking dependencies...
──────────────────────────────────────────
× Please leave this error as an issue
Error: Command failed: ./node_modules/.bin/prisma generate
'.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: './node_modules/.bin/prisma generate',
  stdout: '',
  stderr: "'.' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n'
}

### Capture screen(캡쳐 화면)

![image](https://user-images.githubusercontent.com/6328006/121583946-982d8a00-ca39-11eb-95db-b1f0fac7032c.png)

**Comment by ljlm0402** [comment]
@SayerAljohani 

Thank you for the problem.
I will take measures after confirmation.

**Comment by amantiwari1** [comment]
Same here!

**Comment by ljlm0402** [comment]
@amantiwari1 

Sorry. There are no error cases, so it is difficult to check, so it is delayed. Please understand.

**Comment by ljlm0402** [comment]
@SayerAljohani @amantiwari1 

Please restart this script from an administrative PowerShell
```sh
npm install --global windows-build-tools
```

discussions : https://github.com/prisma/prisma/discussions/5595
